package com.docwei.compiler;

public class Consts {
    //生成的文件的路径
    public static final String PACKAGE_OF_GENERATE_FILE = "com.docwei.arouter.routes";
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "ARouter";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group";
}
